"""Character memory API endpoints."""

from uuid import UUID
from typing import Optional
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.exceptions import AppException
from app.models.memory import CharacterMemory
from app.api.v1.auth import get_current_user_id
from app.services.embedding import embedding_service

router = APIRouter(prefix="/memories", tags=["memories"])


# ---- Request/Response Schemas ----

class CreateMemoryRequest(BaseModel):
    session_id: str
    content: str = Field(..., min_length=1, max_length=2000)
    source: str = Field(default="game_event", pattern="^(game_event|dialogue|choice|system)$")
    character_id: Optional[str] = None


class MemoryResponse(BaseModel):
    id: str
    content: str
    source: str
    character_id: Optional[str] = None
    session_id: Optional[str] = None
    created_at: datetime


class MemoryListResponse(BaseModel):
    memories: list[MemoryResponse]
    total: int


# ---- Endpoints ----

@router.post("", status_code=201)
async def create_memory(
    request: CreateMemoryRequest,
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Create a new character memory."""
    # Validate session_id UUID
    try:
        session_uuid = UUID(request.session_id)
    except ValueError:
        raise AppException("INVALID_SESSION_ID", 400, "Invalid session_id format")
    
    # Validate character_id UUID if provided
    character_uuid = None
    if request.character_id:
        try:
            character_uuid = UUID(request.character_id)
        except ValueError:
            raise AppException("INVALID_CHARACTER_ID", 400, "Invalid character_id format")
    
    # Generate embedding for vector search
    embedding = await embedding_service.generate_embedding(request.content)
    
    # Create memory
    memory = CharacterMemory(
        user_id=UUID(user_id),
        character_id=character_uuid,
        memory_text=request.content,
        embedding=embedding,  # Auto-generated by embedding service (None if unavailable)
        source=request.source,
        source_session_id=session_uuid,
        confidence=1.0,
    )
    
    db.add(memory)
    await db.commit()
    await db.refresh(memory)
    
    return {
        "id": str(memory.id),
        "content": memory.memory_text,
        "source": memory.source,
        "character_id": str(memory.character_id) if memory.character_id else None,
        "session_id": str(memory.source_session_id) if memory.source_session_id else None,
        "created_at": memory.created_at.isoformat(),
    }


@router.get("")
async def list_memories(
    session_id: Optional[str] = Query(None),
    character_id: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    offset: int = Query(0, ge=0),
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """List memories for the current user, optionally filtered by session or character."""
    # Build query
    stmt = select(CharacterMemory).where(CharacterMemory.user_id == UUID(user_id))
    
    # Filter by session_id
    if session_id:
        try:
            session_uuid = UUID(session_id)
            stmt = stmt.where(CharacterMemory.source_session_id == session_uuid)
        except ValueError:
            raise AppException("INVALID_SESSION_ID", 400, "Invalid session_id format")
    
    # Filter by character_id
    if character_id:
        try:
            character_uuid = UUID(character_id)
            stmt = stmt.where(CharacterMemory.character_id == character_uuid)
        except ValueError:
            raise AppException("INVALID_CHARACTER_ID", 400, "Invalid character_id format")
    
    # Order and paginate
    stmt = stmt.order_by(CharacterMemory.created_at.desc()).offset(offset).limit(limit)
    
    result = await db.execute(stmt)
    memories = result.scalars().all()
    
    # BUG-029-012: 批量查询角色名称
    character_ids = list(set(m.character_id for m in memories if m.character_id))
    char_map = {}
    if character_ids:
        from app.models.script import Character
        char_result = await db.execute(
            select(Character).where(Character.id.in_(character_ids))
        )
        char_map = {c.id: c.name for c in char_result.scalars().all()}
    
    # BUG-029-007: 返回总记录数（而非当前页数量）
    count_stmt = select(func.count()).select_from(CharacterMemory).where(CharacterMemory.user_id == UUID(user_id))
    if session_id:
        count_stmt = count_stmt.where(CharacterMemory.source_session_id == session_uuid)
    if character_id:
        count_stmt = count_stmt.where(CharacterMemory.character_id == character_uuid)
    total_result = await db.execute(count_stmt)
    total_count = total_result.scalar() or 0
    
    return {
        "memories": [
            {
                "id": str(m.id),
                "content": m.memory_text,
                "source": m.source,
                "character_id": str(m.character_id) if m.character_id else None,
                "character_name": char_map.get(m.character_id, "未知角色") if m.character_id else None,
                "session_id": str(m.source_session_id) if m.source_session_id else None,
                "created_at": m.created_at.isoformat(),
            }
            for m in memories
        ],
        "total": total_count,
    }


class RecallMemoryItem(BaseModel):
    id: str
    content: str
    source: str
    confidence: float
    similarity: float
    created_at: Optional[str] = None


class RecallMemoryResponse(BaseModel):
    memories: list[RecallMemoryItem]
    total: int
    method: str  # "vector" or "fulltext"


@router.get("/recall")
async def recall_memories(
    query: str = Query(..., min_length=1, max_length=500, description="Search query for similar memories"),
    character_id: Optional[str] = Query(None, description="Filter by character ID"),
    session_id: Optional[str] = Query(None, description="Filter by game session ID"),
    limit: int = Query(5, ge=1, le=20, description="Max results"),
    min_similarity: float = Query(0.3, ge=0.0, le=1.0, description="Minimum cosine similarity"),
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Recall memories by semantic similarity (vector search with full-text fallback).

    Uses OpenAI embeddings (text-embedding-3-small, 1536-dim) for cosine similarity.
    Falls back to ILIKE full-text search when embedding service is unavailable.
    """
    # Validate UUIDs
    if character_id:
        try:
            UUID(character_id)
        except ValueError:
            raise AppException("INVALID_CHARACTER_ID", 400, "Invalid character_id format")
    if session_id:
        try:
            UUID(session_id)
        except ValueError:
            raise AppException("INVALID_SESSION_ID", 400, "Invalid session_id format")

    memories = await embedding_service.recall_memories(
        db=db,
        query=query,
        user_id=user_id,
        character_id=character_id,
        session_id=session_id,
        limit=limit,
        min_similarity=min_similarity,
    )

    # Determine method used
    method = "vector" if any(m["similarity"] != 0.5 for m in memories) else "fulltext"
    if not memories:
        # Try to detect if embedding is available
        provider = await embedding_service._get_provider()
        method = "vector" if provider else "fulltext"

    return {
        "memories": memories,
        "total": len(memories),
        "method": method,
    }


@router.get("/{memory_id}")
async def get_memory(
    memory_id: str,
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Get a single memory by ID."""
    try:
        memory_uuid = UUID(memory_id)
    except ValueError:
        raise AppException("INVALID_MEMORY_ID", 400, "Invalid memory_id format")
    
    stmt = select(CharacterMemory).where(
        CharacterMemory.id == memory_uuid,
        CharacterMemory.user_id == UUID(user_id),
    )
    
    result = await db.execute(stmt)
    memory = result.scalar_one_or_none()
    
    if not memory:
        raise AppException("MEMORY_NOT_FOUND", 404, "Memory not found")
    
    return {
        "id": str(memory.id),
        "content": memory.memory_text,
        "source": memory.source,
        "character_id": str(memory.character_id) if memory.character_id else None,
        "session_id": str(memory.source_session_id) if memory.source_session_id else None,
        "created_at": memory.created_at.isoformat(),
    }
