"""CR-002: add password_resets and discord_configs tables

Revision ID: 552d0ee28507
Revises: 001
Create Date: 2026-07-18 15:45:08.337661
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '552d0ee28507'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_comments_post_id', table_name='comments')
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_posts_user_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_achievements_user_id', table_name='achievements')
    op.drop_table('achievements')
    op.drop_index('idx_collections_user_id', table_name='collections')
    op.drop_table('collections')
    op.alter_column('affection', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('affection', 'level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('affection', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('affection_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_affection_history_user_char', table_name='affection_history')
    op.create_index(op.f('ix_affection_history_user_id'), 'affection_history', ['user_id'], unique=False)
    op.alter_column('cg_assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_memories', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False)
    op.alter_column('character_memories', 'is_compressed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('character_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_memories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_memories_embedding', table_name='character_memories', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_memories_user_char', table_name='character_memories')
    op.alter_column('character_sprites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'dialogue_style',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_checkins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_tasks', 'target',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('daily_tasks', 'claimed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('daily_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_verifications', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('email_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('fragment_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('fragments', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fragments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('game_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('game_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('game_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('game_sessions', 'choice_history',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('game_sessions', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('node_choices', 'affection_delta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('node_choices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_oauth_accounts_user_id', table_name='oauth_accounts')
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.alter_column('password_resets', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('password_resets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_password_resets_token', table_name='password_resets')
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.alter_column('purchases', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('purchases', 'is_mock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('purchases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('share_cards', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('share_cards', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.drop_index('idx_share_cards_user_id', table_name='share_cards')
    op.create_index(op.f('ix_share_cards_user_id'), 'share_cards', ['user_id'], unique=False)
    op.create_foreign_key(None, 'share_cards', 'game_sessions', ['session_id'], ['id'])
    op.drop_column('share_cards', 'title')
    op.drop_column('share_cards', 'share_type')
    op.drop_column('share_cards', 'extra_data')
    op.drop_column('share_cards', 'description')
    op.alter_column('streak_records', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('streak_records', 'max_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('streak_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('subscriptions', 'is_mock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subscriptions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('unlocked_cgs', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('unlocked_scripts', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_preferences', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user_preferences', 'bgm_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_preferences', 'sfx_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_preferences', 'text_speed',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_oauth', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_oauth', 'users', ['oauth_provider', 'oauth_id'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_preferences', 'text_speed',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_preferences', 'sfx_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_preferences', 'bgm_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_preferences', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('unlocked_scripts', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('unlocked_cgs', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'is_mock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('streak_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('streak_records', 'max_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('streak_records', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('share_cards', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('share_cards', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('share_cards', sa.Column('share_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('share_cards', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'share_cards', type_='foreignkey')
    op.drop_index(op.f('ix_share_cards_user_id'), table_name='share_cards')
    op.create_index('idx_share_cards_user_id', 'share_cards', ['user_id'], unique=False)
    op.drop_column('share_cards', 'metadata_json')
    op.drop_column('share_cards', 'session_id')
    op.alter_column('scripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchases', 'is_mock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('purchases', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.create_index('ix_password_resets_token', 'password_resets', ['token'], unique=False)
    op.alter_column('password_resets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_resets', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.create_index('idx_oauth_accounts_user_id', 'oauth_accounts', ['user_id'], unique=False)
    op.alter_column('nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('node_choices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('node_choices', 'affection_delta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_sessions', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('game_sessions', 'choice_history',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('game_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('game_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('game_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fragments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fragments', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fragment_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_verifications', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('daily_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_tasks', 'claimed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('daily_tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('daily_tasks', 'target',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_checkins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'dialogue_style',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('character_sprites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_memories_user_char', 'character_memories', ['user_id', 'character_id'], unique=False)
    op.create_index('idx_memories_embedding', 'character_memories', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('character_memories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_memories', 'is_compressed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('character_memories', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True)
    op.alter_column('cg_assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_affection_history_user_id'), table_name='affection_history')
    op.create_index('idx_affection_history_user_char', 'affection_history', ['user_id', 'character_id'], unique=False)
    op.alter_column('affection_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('affection', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('affection', 'level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('affection', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='collections_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collections_pkey')
    )
    op.create_index('idx_collections_user_id', 'collections', ['user_id'], unique=False)
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('achievement_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='achievements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='achievements_pkey')
    )
    op.create_index('idx_achievements_user_id', 'achievements', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_urls', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('like_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('comment_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_posts_user_id', 'posts', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='comments_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index('idx_comments_post_id', 'comments', ['post_id'], unique=False)
    op.drop_table('discord_configs')
    # ### end Alembic commands ###
