"""CR-002 Wave 2: add recall_emails + free_chat_sessions + users.last_login

Revision ID: c2b84460a40d
Revises: 552d0ee28507
Create Date: 2026-07-18 15:54:36.271673
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b84460a40d'
down_revision: Union[str, None] = '552d0ee28507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_free_chat_sessions_user_id'), 'free_chat_sessions', ['user_id'], unique=False)
    op.create_table('recall_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recall_emails_user_id'), 'recall_emails', ['user_id'], unique=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_index(op.f('ix_recall_emails_user_id'), table_name='recall_emails')
    op.drop_table('recall_emails')
    op.drop_index(op.f('ix_free_chat_sessions_user_id'), table_name='free_chat_sessions')
    op.drop_table('free_chat_sessions')
    # ### end Alembic commands ###
